import { sharingCard } from '../shared/sharing.mjs';
import { commentsEnabled } from './comments.mjs';
import { escapeHtml as e } from './document.mjs';
export { attributionHtml, articleHtml, indexHtml } from '../shared/presentation.mjs';
export function pageHtml(env, { title = 'Blorenge Commoners Association blog', excerpt = 'News and updates from Blorenge Commoners Association.', html = '', slug, private: isPrivate = false, article = false, id, revision, path: explicitPath, interactive = true, sharingImage }) {
  const path = explicitPath || (slug ? `/blog/${slug}/` : '/blog/'), canonical = `${env.ORIGIN}${path}`;
  const card = sharingCard({ sharingImage }, env.ORIGIN);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · Blorenge Commoners Association</title><meta name="description" content="${e(excerpt)}">${isPrivate ? '<meta name="robots" content="noindex,nofollow">' : `<link rel="canonical" href="${e(canonical)}"><meta property="og:type" content="${article ? 'article' : 'website'}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(excerpt)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="${e(card.url)}"><meta property="og:image:width" content="${card.width}"><meta property="og:image:height" content="${card.height}"><meta property="og:image:type" content="${e(card.type)}"><meta property="og:image:alt" content="${e(card.alt)}">`}<link rel="stylesheet" href="/static/blog.css">${interactive ? '<script type="module" src="/static/reader.js"></script>' : ''}</head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="wordmark" href="/"><span class="brand-mark" aria-hidden="true">✳</span> Blorenge Commoners Association</a><nav aria-label="Main"><a data-nav href="/blog/">Blog</a><a href="https://explore.bca.wales">Landscape explorer</a><a href="/account/">Write / account</a></nav></header><main id="main" tabindex="-1" data-post="${e(id || '')}" data-revision="${e(revision || '')}" data-private="${isPrivate}">${html}</main><footer class="site-footer"><div class="footer-heading"><a class="wordmark" href="/blog/">Blorenge Commoners Association</a><p>Landscape. Community. Recovery.</p></div>${interactive ? '<button type="button" id="reset-reveals">Reset image reveals</button><p id="global-status" role="status"></p>' : ''}<a href="/privacy">Privacy and deletion</a>${commentsEnabled(env) ? ' · <a href="/blog/guidelines/">Community guidelines</a>' : ''}</footer></body></html>`;
}
