import { escapeHtml as e } from './document.mjs';
export function attributionHtml(attribution) {
  const name = e(attribution?.name || 'BCA Wales contributor');
  return attribution?.link ? `<a href="${e(attribution.link)}" target="_blank" rel="noopener noreferrer" aria-label="${name} on Facebook (opens a new tab; access may be restricted)">${name}</a>` : name;
}
export function pageHtml(env, { title = 'BCA Wales blog', excerpt = 'News and updates from BCA Wales.', html = '', slug, private: isPrivate = false, article = false, id, revision }) {
  const path = slug ? `/blog/${slug}/` : '/blog/', canonical = `${env.ORIGIN}${path}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · BCA Wales</title><meta name="description" content="${e(excerpt)}">${isPrivate ? '<meta name="robots" content="noindex,nofollow">' : `<link rel="canonical" href="${e(canonical)}"><meta property="og:type" content="${article ? 'article' : 'website'}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(excerpt)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="${e(env.ORIGIN)}/static/share.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:type" content="image/png"><meta property="og:image:alt" content="BCA Wales — landscape, community and recovery">`}<link rel="stylesheet" href="/static/blog.css"><script type="module" src="/static/reader.js"></script></head><body><a class="skip" href="#main">Skip to content</a><header><a href="/">BCA Wales</a><nav aria-label="Main"><a data-nav href="/blog/">Blog</a><a href="https://explore.bca.wales">Landscape explorer</a><a href="/account/">Write / account</a></nav></header><main id="main" tabindex="-1" data-post="${e(id || '')}" data-revision="${e(revision || '')}" data-private="${isPrivate}">${html}</main><footer><button type="button" id="reset-reveals">Reset image reveals</button><p id="global-status" role="status"></p><a href="/blog/privacy/">Privacy and deletion</a> · <a href="/blog/guidelines/">Community guidelines</a></footer></body></html>`;
}
export function articleHtml(article) {
  return `<article><h1>${e(article.title)}</h1><p class="byline">${attributionHtml(article.attribution)} · Updated <time datetime="${new Date(article.updatedAt * 1000).toISOString()}">${e(new Date(article.updatedAt * 1000).toLocaleDateString('en-GB', { timeZone: 'UTC', dateStyle: 'long' }))}</time></p>${article.html}</article><section id="comments" aria-label="Comments"><h2>Comments</h2><p>Loading comments…</p></section>`;
}
export function indexHtml(posts) {
  return `<h1>BCA Wales blog</h1><p>Stories from our landscape and community.</p>${posts.length ? posts.map(p => `<article><h2><a data-nav href="/blog/${e(p.slug)}/">${e(p.title)}</a></h2><p>${e(p.excerpt)}</p><p>${attributionHtml(p.attribution)}</p></article>`).join('') : '<p>No posts have been published yet.</p>'}`;
}
